### ISSUE TITLE
Unable to troubleshoot gulp-less errors

### ISSUE THREAD

**Issue by philipwhiuk** [stevelacy/gulp-less#261]
Instead of useful output I get an error indicating readable-stream issues.

```
Potentially unhandled rejection [2] Error: no writecb in Transform class
    at afterTransform (/home/pwhiteho/git/*/node_modules/gulp-less/node_modules/readable-stream/lib/_stream_transform.js:74:40)
    at TransformState.afterTransform (/home/pwhiteho/git/*/node_modules/gulp-less/node_modules/readable-stream/lib/_stream_transform.js:58:12)
    at /home/pwhiteho/git/*/node_modules/gulp-less/index.js:58:14
    at tryCatchReject (/home/pwhiteho/git/*/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/home/pwhiteho/git/*/node_modules/when/lib/makePromise.js:804:4)
    at Rejected.when (/home/pwhiteho/git/*/node_modules/when/lib/makePromise.js:625:4)
    at Pending.run (/home/pwhiteho/git/*/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/home/pwhiteho/git/*/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/home/pwhiteho/git/*/node_modules/when/lib/Scheduler.js:27:9)
```

package.json

```
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-concat-css": "^2.2.0",
    "gulp-minify-css": "^1.1.1",
    "gulp-uglify": "^1.1.0",
    "gulp-util": "^3.0.4",
    "gulp-less": "^3.3.0",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-watch": "^4.3.5",
    "gulp-batch": "^1.0.5",
    "gulp-add-src": "^0.2.0",
    "gulp-eslint": "^1.0.0",
    "eslint-plugin-react": "^3.6.3",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.0.0",
    "browserify": "^10.2.4",
    "babelify": "^6.1.2",
    "babel": "^5.8.29",
    "envify": "^3.0.0",
    "gulp-mocha": "^2.1.3",
    "proxyquire": "^1.7.3",
    "sinon": "^1.17.2",
    "chai": "^3.4.0",
    "resolve": "^1.1.6",
    "lodash": "^3.10.1"
  },
  "dependencies": {
    "bootstrap": "^3.3.5",
    "classnames": "^2.1.2",
    "es6-shim": "^0.35.0",
    "history": "^1.12.0",
    "immutable": "^3.7.5",
    "jquery": "^2.1.4",
    "moment": "^2.10.3",
    "numeral": "1.5.3",
    "object-assign": "^3.0.0",
    "react": "^0.14.2",
    "react-bootstrap": "^0.30.6",
    "react-bootstrap-toggle": "1.2.14",
    "react-bootstrap-slider": "1.0.3",
    "react-dom": "^0.14.2",
    "react-redux": "^4.0.0",
    "react-router": "^0.13.4",
    "redux": "^3.0.4",
    "redux-actions": "^0.8.0",
    "redux-mock-store": "0.0.6",
    "redux-thunk": "1.0.3"
  }
```

Gulp task:

```
gulp.src('./gulp/javascripts/**/*.js')
        .pipe(eslint([".eslintrc"]))
        .pipe(eslint.format())
        .pipe(eslint.failAfterError())
```

Any advice?

**Comment by philipwhiuk** [comment]
One scenario this seems to happen is if it can't find an `@import` file

**Comment by stevelacy** [comment]
Are you using any error handler such as gulp-plumber to catch the errors?
