### ISSUE TITLE
less version 3.0.4 is not currently supported

### ISSUE THREAD

**Issue by txiaocao** [stevelacy/gulp-less#293]
/Users/maoke/project/kemao/project-tools/node_modules/accord/lib/index.js:29
      throw new Error(name + " version " + version + " is not currently supported");
            ^
Error: less version 3.0.4 is not currently supported
    at Object.exports.load (/Users/maoke/project/kemao/project-tools/node_modules/accord/lib/index.js:29:13)
    at Object.<anonymous> (/Users/maoke/project/kemao/project-tools/node_modules/gulp-less/index.js:9:29)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

**Comment by viki719632** [comment]
when I try to use the gulp to compile the less files,I have the same error like 
"less version 3.0.4 is not currently supported";
It seem that the error is throw from less not gulp.
I try to reduce my less version.
like: npm i -D less@2.7.0
